name: test
on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: g++ --version
      - name: run test
        run: make test

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: g++ --version
      - name: run test
        run: make test
