name: test
on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: g++ --version
      - name: run test
        run: make test

  macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - run: g++ --version
      - name: run test
        run: make test

  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: run test
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          nmake -f Makefile.msvc test
